[grvy]: include -h tests in standalone binaries

diff --git a/test/gadd b/test/gadd
--- a/test/gadd
+++ b/test/gadd
@@ -12,6 +12,7 @@ echo "-------------------------------------------------------"
 # --------------------------------------------------------------------------
 
 GADD=../src/gadd
+REF_DIR=ref_files
 TEST_FILE=.test.h5
 
 # Compiled binaries must exist
@@ -25,7 +26,30 @@ if test -e $TEST_FILE ;then
     rm -f $TEST_FILE
 fi
 
-# Run the binary and make sure it exits with zero status
+
+# -------------------------------------
+# First, run the binary with help option
+# -------------------------------------
+
+$GADD -h >& $TEST_FILE || exit 1
+
+if test ! -s $TEST_FILE ; then
+    echo "${0}: No output generated from $GADD"
+    exit 1
+fi
+
+diff $TEST_FILE $REF_DIR/gadd.help || exit 1
+
+# Clean up
+
+if test -e $TEST_FILE ; then
+    rm -f $TEST_FILE
+fi
+
+# --------------------------------------------------------------
+# Second, run the binary and make sure it generates output
+# (will be used as input for subsequent gdump test)
+# --------------------------------------------------------------
 
 $GADD -q -c "acomment" -m "mymachine"   -j "12345" -p 42 -r "r2222" -f 65 13.45  "example1" $TEST_FILE || exit 1
 $GADD -q -c "commentb" -m "mymachine"   -j "54321" -p  1 -r "r2223" -f 65  2.45  "example1" $TEST_FILE || exit 1
@@ -35,3 +59,5 @@ if test ! -s $TEST_FILE ; then
     echo "${0}: No output generated from $GADD"
     exit 1
 fi
+
+exit 0
diff --git a/test/gdump b/test/gdump
--- a/test/gdump
+++ b/test/gdump
@@ -20,7 +20,7 @@ if test ! -x $GDUMP ; then
 fi
 
 if test ! -s $TEST_FILE ; then
-    echo "${0}: No output generated from $GADD"
+    echo "${0}: No output generated from $GDUMP"
     exit 1
 fi
 
@@ -48,6 +48,25 @@ cat $TEST_DIR/yourmachine/example2 | grep -v "^#"  | awk '{$2=$3=$4="";print}' >
 
 diff $TEST_DIR/mymachine/example1.pruned $REF_DIR/$TEST_DIR/mymachine/example1.pruned >& /dev/null || exit 1
 diff $TEST_DIR/mymachine/example1.pruned $REF_DIR/$TEST_DIR/mymachine/example1.pruned >& /dev/null || exit 1
+
+# Clean up
+
+if test -e $TEST_FILE ; then
+    rm -f $TEST_FILE
+fi
+
+# -------------------------------------
+# Now, run the binary with help option
+# -------------------------------------
+
+$GDUMP -h >& $TEST_FILE || exit 1
+
+if test ! -s $TEST_FILE ; then
+    echo "${0}: No output generated from $GDUMP"
+    exit 1
+fi
+
+diff $TEST_FILE $REF_DIR/gdump.help || exit 1
 
 # Clean up
 
